"""add_commission_fields

Revision ID: 23ff6f3764fe
Revises: c15673079363
Create Date: 2026-05-06 13:04:29.172549

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '23ff6f3764fe'
down_revision: str | None = 'c15673079363'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commissions', sa.Column('doctors_count', sa.Integer(), nullable=False))
    op.add_column('commissions', sa.Column('connected_computers_count', sa.Integer(), nullable=False))
    op.add_column('commissions', sa.Column('internet_type', sa.String(length=50), nullable=True))
    op.add_column('commissions', sa.Column('has_local_network', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commissions', 'has_local_network')
    op.drop_column('commissions', 'internet_type')
    op.drop_column('commissions', 'connected_computers_count')
    op.drop_column('commissions', 'doctors_count')
    # ### end Alembic commands ###
