"""add telegram fields to user

Revision ID: a509dec77378
Revises: b679eb686b1e
Create Date: 2026-05-06 17:03:13.650558

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a509dec77378'
down_revision: str | None = 'b679eb686b1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
