"""add route_cache table

Revision ID: b679eb686b1e
Revises: bd16ff0d4af8
Create Date: 2026-05-06 17:01:05.149279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'b679eb686b1e'
down_revision: Union[str, None] = 'bd16ff0d4af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_key', sa.String(), nullable=False),
    sa.Column('destination_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('geometry_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_cache_destination_key'), 'route_cache', ['destination_key'], unique=False)
    op.create_index(op.f('ix_route_cache_id'), 'route_cache', ['id'], unique=False)
    op.create_index(op.f('ix_route_cache_origin_key'), 'route_cache', ['origin_key'], unique=False)
    op.create_index('ix_route_lookup', 'route_cache', ['origin_key', 'destination_key'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=500), nullable=False),
    sa.Column('auth', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscriptions')
    op.drop_index('ix_route_lookup', table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_origin_key'), table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_id'), table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_destination_key'), table_name='route_cache')
    op.drop_table('route_cache')
    # ### end Alembic commands ###
