"""add_settlement_id_to_task

Revision ID: bd16ff0d4af8
Revises: 23ff6f3764fe
Create Date: 2026-05-06 15:13:08.993113

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'bd16ff0d4af8'
down_revision: str | None = '23ff6f3764fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('settlement_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'settlement_id')
    # ### end Alembic commands ###
