"""add_region_engineer_fields

Revision ID: c15673079363
Revises: cc566e91b884
Create Date: 2026-05-06 11:54:29.886518

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c15673079363'
down_revision: str | None = 'cc566e91b884'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add as nullable first
    op.add_column('medical_researches', sa.Column('is_connected', sa.Boolean(), nullable=True))
    op.add_column('medical_researches', sa.Column('staff_trained', sa.Boolean(), nullable=True))
    op.add_column('medical_researches', sa.Column('has_data_stream', sa.Boolean(), nullable=True))
    
    # Set default for existing rows
    op.execute("UPDATE medical_researches SET is_connected = false, staff_trained = false, has_data_stream = false")
    
    # Make non-nullable
    op.alter_column('medical_researches', 'is_connected', nullable=False)
    op.alter_column('medical_researches', 'staff_trained', nullable=False)
    op.alter_column('medical_researches', 'has_data_stream', nullable=False)
    op.add_column('regions', sa.Column('engineer_name', sa.String(length=255), nullable=True))
    op.add_column('regions', sa.Column('engineer_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'engineer_phone')
    op.drop_column('regions', 'engineer_name')
    op.drop_column('medical_researches', 'has_data_stream')
    op.drop_column('medical_researches', 'staff_trained')
    op.drop_column('medical_researches', 'is_connected')
    # ### end Alembic commands ###
