"""add_research_models_v2

Revision ID: cc566e91b884
Revises: b252a82bbe7b
Create Date: 2026-05-06 11:46:47.594242

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'cc566e91b884'
down_revision: str | None = 'b252a82bbe7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_researches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('research_type', sa.String(length=50), nullable=False),
    sa.Column('input_method', sa.String(length=20), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=True),
    sa.Column('specialist_name', sa.String(length=200), nullable=True),
    sa.Column('specialist_position', sa.String(length=200), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('problems', sa.Text(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('image_source', sa.String(length=50), nullable=True),
    sa.Column('has_conclusion', sa.Boolean(), nullable=False),
    sa.Column('conclusion_source', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['medical_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['medical_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_researches')
    # ### end Alembic commands ###
